### ISSUE TITLE
usage of HMMer format profiles

### ISSUE THREAD

**Issue by margoschuller** [soedinglab/hh-suite#69]
hh-suite v2.0.16 from the Linux tar release

I would like to use the hh-suite similarity searches using HMMer format files. hh-suites documentation states that it is able to handle HMMer format files, but I have not been able to make it to work.

What I tried is running hhsearch using HMMer format files like described in the documentation, though it gave me an ERROR and no output. This command line does work for the hh-suite profiles.

command used:
`multithread.pl '*.hmm' 'hhsearch -i $file -d hmm_db' -cpu 15`

ERROR code:
`Use of HMMER format as input will result in severe loss of sensitivity!`

So my questions are:
Can I use hh-suite with HMMer profiles? And how should I do this?
Do you have extra information or feedback about the reduced performance of hh-suite when using HMMer format profiles apart?

With kind regards, 

Margo Schuller

**Comment by margoschuller** [comment]
Hi Milot, 

Thank you for your reply, but what I really want to know if it is possible at all to use HMMer profiles if you do not have the original alignments?

I also tested hhsuite version-3.0-beta.3-Linux, and that also did not work.

Best regards,

Margo

**Comment by milot-mirdita** [comment]
Could you post the log please? Does it crash or say anything unusual? It should be working, just not extremly well.

**Comment by margoschuller** [comment]
Hi yes, this is all I have, 

I tried running hhmake on a HMMER3 and HMMER2 formatted file, I attached the HMMER3 file and the output of the hhmake. 
I got this error message and an "empty" output (see attached files)
- 11:08:01.706 ERROR: Use of HMMER format as input will result in severe loss of sensitivity!

Done


[VOG0001.hhm.txt](https://github.com/soedinglab/hh-suite/files/1332521/VOG0001.hhm.txt)
[VOG0001.hmm.txt](https://github.com/soedinglab/hh-suite/files/1332522/VOG0001.hmm.txt)

**Comment by TaehyungKwon** [comment]
Hi all, 
I still have a same error when I use hhmake for HMMER 3 format!

**Comment by milot-mirdita** [comment]
You need to create new profiles from the original MSAs. Using hmmer profiles isn't supported anymore.

**Comment by TaehyungKwon** [comment]
@milot-mirdita 
Ah, alright. Thank you for the clarification!

**Comment by LicoriceLin** [comment]
> You need to create new profiles from the original MSAs. Using hmmer profiles isn't supported anymore.

These hmm relevant operations are still in HH-suite's documentation. How about remove them to avoid future complain?
![image](https://github.com/soedinglab/hh-suite/assets/93641868/4db0e076-6936-4172-a402-74aada5cfab6)

**Comment by LicoriceLin** [comment]
> > You need to create new profiles from the original MSAs. Using hmmer profiles isn't supported anymore.
> 
> These hmm relevant operations are still in HH-suite's documentation. How about remove them to avoid future complain? ![image](https://private-user-images.githubusercontent.com/93641868/308672362-4db0e076-6936-4172-a402-74aada5cfab6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDU1NTYsIm5iZiI6MTcwOTE0NTI1NiwicGF0aCI6Ii85MzY0MTg2OC8zMDg2NzIzNjItNGRiMGUwNzYtNjkzNi00MTcyLWE0MDItNzRhYWRhNWNmYWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE4MzQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZjYyMjI2YTQzZDAwMzMxMjc2ZDdkN2IxY2I1ODE0NmRkMzk0YWE5ZTI5ZGMwNjFhNGE4M2U5N2ExM2MxNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.riR5YE2Gnl2MFYbKOMqiK0JQipDQZBpYKG5MTZkk7Uo)

As I executed this command, it reported error directly and generated a null .hhm file
![image](https://github.com/soedinglab/hh-suite/assets/93641868/3e5dcadc-ffe3-4013-b02c-70897c25619a)
